app/mixins.py, app/templates/components/bootstrap5_form.html, application/forms.py
=> Fixed issue visible

DEV.md
Co-authored-by: Silvia Arellano <silviaarellanogarcia@users.noreply.github.com>
=> Changed documentation

app/hackathon_variables.py, app/log.py, app/settings.py
=> Added mails

.github/workflows/docker.yml, app/templates/components/theme_switch.html
=> Production

.github/workflows/docker.yml
=> Made dockerhub require CI Fix

app/utils.py, application/models.py
=> Fixed issues

.github/workflows/django.yml, app/settings.py, requirements.txt
Added validation for passwords
Fixes #
References #
=> Validation

app/settings.py, user/forms.py, user/templates/auth.html, user/templates/password_reset.html, user/views.py
=> Fixed bugs

app/settings.py
=> Added security

app/allauth.py, app/settings.py, app/template.py, app/urls.py, requirements.txt, user/templates/auth.html
Added the option of doing Log In with social accounts, such as GitHub.
Fixes #
References #
=> Social accounts

application/admin.py
=> Fixed collectstatic bug

stats/base.py
=> Fixed stats

app/templates/mails/components/socials.html, application/apps.py, application/emails.py, application/management/commands/expire_invitations.py, application/templates/application_home/user_applications.html, application/templates/mails/application_last_reminder.html, review/emails.py, review/templates/mails/application_invite.html, review/templates/mails/application_invite.txt, review/views.py
=> Fixed mails & invitations & logs

application/views.py
=> Fixed apply bug

stats/base.py, stats/stats.py, stats/templates/stats.html
=> Added extras on stats

requirements.txt
=> Fixed vulnerability

app/templates/base.html, application/templates/application_home/apply.html, application/templates/application_home/user_applications.html, user/templates/auth.html
=> Fixed mobile ui

app/templates/base.html, event/templates/checkin_user.html, user/templates/auth.html, user/templates/forgot_password.html, user/templates/needs_verification.html, user/templates/password_reset.html
=> Updated ui

app/static/css/theme.scss, app/templates/components/table.html, review/templates/application_list.html, review/views.py
=> Added email copy

application/views.py
=> Fixed email verification on register

application/signals.py
=> Fixed signals

friends/views.py
=> Fixed permission denied

friends/views.py
=> Fixed permission friends

review/tables.py, review/views.py
=> Fixed invitation bug

app/utils.py, application/forms/base.py, user/forms.py
=> Fixed bug with instances

app/settings.py, review/views.py
=> Added friends on detail

review/templates/application_list.html
=> Fixed issue

app/tables.py, application/views.py, review/forms.py, review/tables.py, review/templates/application_detail.html
=> Fixed some issues

review/templates/application_detail.html
=> Fixed label bug

application/templates/application_home/user_applications.html, event/templates/checkin_user.html, event/views.py
- Added possibility to not scan qr on checkin and autogenerate qr string
- Added pop up when clicked qr code to make it more dificult to copy and get into the event
Fixes #
References #
=> Fixed some issues with checkin

app/emails.py, application/emails.py, application/management/commands/expire_invitations.py, friends/views.py, review/emails.py, review/templates/application_list.html, review/views.py
- Implemented system to send massive mails
Fixes #
References #
=> Implemented massive email service

run.sh
=> Fixed crons

app/settings.py, app/template.py, event/urls.py
=> Fixed, my bad

event/meals/models.py, event/meals/tables.py
=> Added row meals

.github/workflows/django.yml, .github/workflows/docker.yml
=> Removed cache on build and added support to python 3.11
